/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "tertiary-container": "#008096",
              "surface-bright": "#fff8f7",
              "surface-container": "#ffe9e6",
              "surface-variant": "#fadcd8",
              "surface-container-high": "#ffe2de",
              "inverse-primary": "#ffb4aa",
              "outline": "#906f6b",
              "tertiary": "#006577",
              "on-tertiary-fixed": "#001f26",
              "inverse-on-surface": "#ffedea",
              "on-tertiary-fixed-variant": "#004e5c",
              "outline-variant": "#e5beb8",
              "on-primary-fixed": "#410001",
              "error-container": "#ffdad6",
              "on-secondary-container": "#616363",
              "text-meta": "#828282",
              "on-primary-fixed-variant": "#930008",
              "success-green": "#2B8A3E",
              "on-surface-variant": "#5c403c",
              "primary": "#b71415",
              "tertiary-fixed-dim": "#6dd4ee",
              "on-secondary": "#ffffff",
              "on-tertiary": "#ffffff",
              "belia-red-deep": "#E63A30",
              "surface-dim": "#f1d3cf",
              "on-background": "#271715",
              "secondary-fixed": "#e2e2e2",
              "primary-fixed": "#ffdad5",
              "text-primary": "#1A1A1A",
              "on-surface": "#271715",
              "on-secondary-fixed": "#1a1c1c",
              "secondary-fixed-dim": "#c6c6c7",
              "text-secondary": "#4A4A4A",
              "on-primary": "#ffffff",
              "primary-fixed-dim": "#ffb4aa",
              "divider": "#EEEEEE",
              "surface-tint": "#F9F0F0",
              "surface-container-highest": "#fadcd8",
              "secondary": "#5d5f5f",
              "on-primary-container": "#fffbff",
              "error": "#ba1a1a",
              "on-secondary-fixed-variant": "#454747",
              "belia-red": "#EE4036",
              "on-error-container": "#93000a",
              "primary-container": "#db322b",
              "secondary-container": "#dfe0e0",
              "tertiary-fixed": "#acedff",
              "background": "#fff8f7",
              "surface-container-lowest": "#ffffff",
              "surface-container-low": "#fff0ee",
              "on-tertiary-container": "#f9fdff",
              "inverse-surface": "#3e2c2a",
              "on-error": "#ffffff",
              "surface": "#fff8f7"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "section-desktop": "64px",
              "base": "8px",
              "element-gap": "16px",
              "section-mobile": "48px",
              "margin": "32px",
              "card-padding": "24px",
              "gutter": "24px"
      },
      "fontFamily": {
              "headline-sm": ["Plus Jakarta Sans"],
              "body-md": ["Inter"],
              "label-md": ["Inter"],
              "headline-md": ["Plus Jakarta Sans"],
              "headline-lg": ["Plus Jakarta Sans"],
              "hero-display": ["Playfair Display"],
              "body-sm": ["Inter"],
              "body-lg": ["Inter"]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
